version: '3.4'

services:
  consul:
    image: consul:latest
    container_name: consul

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
      args:
        - CONSUL_HOST=consul
        - CONSUL_PORT=8500
    depends_on:
      - consul
    deploy:
      replicas: 2

  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
      args:
        - CONSUL_HOST=consul
        - CONSUL_PORT=8500
    depends_on:
      - consul
    ports:
      - 5000:80