version: '3.4'

services:
  consul:
    image: consul:latest
    container_name: consul

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
      args:
        - CONSUL_HOST
        - CONSUL_PORT
    depends_on:
      - consul
    deploy:
      replicas: ${WEBAPI_REPLICAS}

  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
      args:
        - CONSUL_HOST
        - CONSUL_PORT
    depends_on:
      - consul
    ports:
      - ${GATEWAY_PORT}:80