version: '3.4'

services:
  consul:
    image: consul:latest
    container_name: consul

  identity_server:
    image: ${DOCKER_REGISTRY-}ids4
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    ports:
      - ${IDENTITY_SERVER_PORT}:80

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
      args:
        - CONSUL_HOST
        - CONSUL_PORT
        - DB_CONNECTION_STRING
    depends_on:
      - consul
    deploy:
      replicas: ${WEBAPI_REPLICAS}

  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
      args:
        - CONSUL_HOST
        - CONSUL_PORT
        - ACCESS_TOKEN_URL=http:\/\/identity_server
    depends_on:
      - consul
      - identity_server
    ports:
      - ${GATEWAY_PORT}:80
