version: '3.4'

services:
  webapplication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  consumer:


  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

