version: '3.4'

services:
  webapplication:
    image: ${DOCKER_REGISTRY-}webapplication:dev
    build:
      context: ./WebApplication
      dockerfile: Dockerfile
    ports:
      - "8001:80"
  consumer:
    image: ${DOCKER_REGISTRY-}consumer
    build:
      context: .
      dockerfile: Consumer/Dockerfile


  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile


  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile

